name: P0-Tutorial
on:
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-20.04
    env:
      OS: ubuntu-20.04
      PYTHON: '3.6'
    permissions:
      pull-requests: write
      issues: write
      discussions: write
    steps:
    - uses: actions/checkout@master
    
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.6

    - name: 'test tutorial'
      run: |
        cd tutorial
        python autograder.py | sed '/FAIL/w /tmp/output'
        cd ..
        echo score = $(echo 9-$(bash check_grade.sh) | bc) > score.txt # score
        cat score.txt

    - name: 'add comment'
      run: |
        COMMENT=$(cat score.txt)
        pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        echo "https://api.github.com/repos/${{ github.repository }}/issues/${pull_number}/comments"
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -d "{\"body\":\"Test Results: ${COMMENT} \"}" "https://api.github.com/repos/${{ github.repository }}/issues/${pull_number}/comments"

    - name: 'check error'
      run: bash check_error.sh
