name: P0-Tutorial
on:
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-20.04
    env:
      OS: ubuntu-20.04
      PYTHON: '3.6'
    permissions: write-all

    steps:
    - uses: actions/checkout@master
    
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.6

    - name: 'test tutorial'
      run: |
        cd tutorial
        python autograder.py | sed '/FAIL/w /tmp/output'
        cd ..
        echo score = $(echo 9-$(bash check_grade.sh) | bc) > score.txt # score
        cat score.txt

    - name: Add comment to PR
      env:
        URL: ${{ github.event.pull_request.comments_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        COMMENT=$(cat score.txt)
        echo $URL
        curl \
          -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: token ${{ secrets.PAT }}" \
          --data '{ "body": "$COMMENT" }' \
          $URL

    - name: 'check error'
      run: bash check_error.sh
